name: dgit-updater

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '0 11 * * 1'  # every monday at 7:00 https://crontab.guru/#0_7_*_*_1
  workflow_dispatch:

jobs:
  image:
    name: git-updater
    runs-on: ubuntu-20.04
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "Test clone"
        run: python git-updater.py
      - name: "Test update"
        run: python git-updater.py
